import { CohereClientV2 } from "cohere-ai";
import { replyInteraction, editInteractionMsg, createEmbed } from "../methods";

export async function summarize(interaction) {
  await replyInteraction(
    interaction,
    `⌛ Summarizing recent messages. Please wait.`,
    true
  );

  const messagesRes = await fetch(
    `https://discord.com/api/v10/channels/${interaction.channel_id}/messages?limit=100`,
    {
      method: "GET",
      headers: {
        Authorization: `Bot ${DISCORD_BOT_TOKEN}`,
      },
    }
  );
  if (!messagesRes.ok) {
    return await editInteractionMsg(
      interaction,
      `❌ Failed to fetch messages: ${messagesRes.status} ${messagesRes.statusText}`
    );
  }
  const messages = await messagesRes.json();
  const formattedMessages = messages
    .filter(
      (msg) =>
        !msg.author.bot &&
        msg.content &&
        !msg.content.startsWith("http") &&
        !/^<@!?(\d+)>$/.test(msg.content)
    )
    .map((msg) => `${msg.author.global_name}: ${msg.content}`)
    .reverse()
    .join("\n");
  const cohere = new CohereClientV2({
    token: COHERE_API_KEY,
  });
  const prompt = `You will be given around 100 chat messages in the format:\n[Name]: [Message]\n\nYour task:\n1. Summarize the overall conversation concisely (no more than 5-7 sentences max, but can be fewer if there is not enough content).\n2. Focus on the main topics, agreements, disagreements, or decisions.\n3. Do NOT include vulgar, offensive, or inappropriate language—even if it appeared in the original text.\n4. Keep the summary professional, neutral in tone, and easy to skim.\n5. Do not list every single message. Only highlight major themes or outcomes.\n6. Only reply to this prompt with the summary and no extra text, as this will be displayed to the user.\nIf any user made a notable point, contribution, or decision, mention them by name. Highlight their name using bold text formatting (two ** around the name, e.g. **Name**)\n\nNow here are the messages:\n${formattedMessages}`;
  const response = await cohere.chat({
    model: "command-a-03-2025",
    messages: [
      {
        role: "user",
        content: prompt,
      },
    ],
  });
  const summary = response.message.content[0].text;
  const embed = await createEmbed(
    "Chat Summary",
    summary,
    0x00ae86,
    "LinkSage - Please note this summary was generated by an AI model and may not be 100% accurate. Responses will be logged for safety and quality purposes.",
    null,
    [
      {
        name: "Messages Analyzed",
        value: `${formattedMessages.split("\n").length}`,
        inline: true,
      },
    ]
  );
  await editInteractionMsg(
    interaction,
    `✅ Summary complete! View details below.`,
    embed
  );
  console.log(
    `AI Summary triggered in guild ${interaction.guild_id} by user ${interaction.member.user.id}. Content: ${summary}`
  );
}
